### ISSUE TITLE
Maven installer: `.\mvnw` not found

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#404]
```
Error: An error occurred while running the command: .\mvnw -Dplugin=com.appland:appmap-maven-plugin help:describe
>  .\mvnw -Dplugin=com.appland:appmap-maven-plugin help:describe was not found. Verify the command can be found in your PATH and try again.
   at ChildProcess.<anonymous> (@appland\appmap\built\src\cmds\agentInstaller\commandRunner.js:78:24)
   at ChildProcess.emit (events.js:321:20)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
   at onErrorNT (internal/child_process.js:467:16)
   at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

OS is Windows, Maven wrappers exist in the directory.

**Comment by apotterri** [comment]
> I'm not sure that Windows has a dot - forwardslash concept
It does, but the script to invoke on Windows is named `mvnw.cmd`.

This is fixed by #406.
