### ISSUE TITLE
Attempt to install with `null` installer

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#454]
```
TypeError: Cannot read property 'name' of undefined
   at AgentInstallerProcedure.getEnvironmentForDisplay (./node_modules/@appland/appmap/built/src/cmds/agentInstaller/agentProcedure.js:22:44)
   at AgentInstallerProcedure.run (./node_modules/@appland/appmap/built/src/cmds/agentInstaller/agentInstallerProcedure.js:20:28)
   at Object.handler (./node_modules/@appland/appmap/built/src/cmds/agentInstaller/install-agent.js:147:44)
```

**Comment by apotterri** [comment]
This was fixed by https://github.com/applandinc/appmap-js/pull/468/files#diff-dc3b7928ea4d14d42b04383ef3a1e7f40071114b5a664054c6b843e29ed59fbaR230 .

The missing await meant that we'd try to use the installer before the Promise had been resolved, resulting in this error.
