### ISSUE TITLE
Installer: error when installing into Rails sample app (and other multi-installer projects)

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#470]
The installer shows an error before user can choose the installer (and the error obscures the 2nd choice).

```shell
npx @appland/appmap@latest install
? Multiple project types were found in /Users/ptrdvrk/work/github/ruby/sample_app_6th_ed. Select one to continue. (Use arrow keys)
❯ Bundler
  npm Installing AppMap agent for ....
! Installation failed. View error details? (Y/n)
```

```shell
TypeError: Cannot read properties of undefined (reading 'name')
    at AgentInstallerProcedure.getEnvironmentForDisplay (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/agentProcedure.js:26:44)
    at AgentInstallerProcedure.run (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/agentInstallerProcedure.js:20:28)
    at _handler (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/install-agent.js:123:40)
    at async Object.handler (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/install-agent.js:207:35)
TypeError: Cannot read properties of undefined (reading 'name')
    at AgentInstallerProcedure.getEnvironmentForDisplay (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/agentProcedure.js:26:44)
    at AgentInstallerProcedure.run (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/agentInstallerProcedure.js:20:28)
    at _handler (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/install-agent.js:123:40)
    at async Object.handler (/Users/ptrdvrk/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/install-agent.js:207:35)
```

**Comment by ptrdvrk** [comment]
fixed
